name: Push branch

on:
  push:
    branches:
      - 'test-branch'

jobs:
  pushed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Echo messages
      run: |
        output=$( python save_formated_pr_body.py ${{ github.event.pull_request.body }} )
        echo "::set-output name=content::$output"
      id: pr_body
      working-directory: .github/workflows/
    - name: Print pr
      run: echo "${{ steps.pr_body.outputs.content }}"
