name: Promotion dev1->prod1 Slack notification
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
jobs:
  promoted_to_prod:
    if: |
      (
      github.event.pull_request.merged == true
      )
    runs-on: ubuntu-latest
    steps:
    - name: PR Log title
      run: |
        echo "New promotion: ${{ github.event.pull_request.title }}"
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: PR Format body
      shell: bash
      working-directory: .github/workflows/changelog/
      # Multiline strings from: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      env:
        BODY: ${{ github.event.pull_request.body }}
        PR_SHA: ${{ github.event.pull_request.head.sha }}
        A: <https://github.com/NomadHealth/nomad-env/pull/${{ github.event.pull_request.pull_number }}|PR Url>
      run: |
        PR_URL: "<https://$GITHUB_SERVER_URL/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY/pull/${{ github.event.pull_request.pull_number }}|PR Url>"
        GITHUB_PARAMS="{ 'actor': $GITHUB_ACTOR, 'repo': $GITHUB_REPOSITORY, 'ref': $GITHUB_REF, 'pr_url': $PR_URL }"
        python3 save_formated_pr_body.py "$BODY" "$GITHUB_PARAMS"> result.txt
        PR_FORMATTED_BODY=$(cat result.txt)
        echo "PR_FORMATTED_BODY<<EOF" >> $GITHUB_ENV
        echo "$PR_FORMATTED_BODY" >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Slack Notify
      shell: bash
      env:
        # Title won't render if blocks present but will but it will show up in notifications
        # https://api.slack.com/messaging/attachments-to-blocks#fallback_text
        TITLE: "Changelog notification for a Nomad software promotion"
        BLOCKS: ${{ env.PR_FORMATTED_BODY }}
      run: |
          curl --location --request POST "${{ secrets.SLACK_WEBHOOK }}" \
          --header 'Content-type: application/json' \
          --data "{\"channel\": \"#changelog\", \"username\": \"ghActionsBot\", \"icon_emoji\": \":github:\", "text": \"$TITLE\", "blocks": $BLOCKS}"
