name: Promotion dev1->prod1 Slack notification
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
jobs:
  promoted_to_prod:
    if: |
      (
      github.event.pull_request.merged == true
      )
    runs-on: ubuntu-latest
    steps:
    - name: Log step
      run: |
        echo "New promotion: ${{ github.event.pull_request.title }}"
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Run script
      working-directory: .github/workflows/changelog/
      # Multiline strings tip from: https://trstringer.com/github-actions-multiline-strings/
      run: |
        python3 save_formated_pr_body.py "${{ github.event.pull_request.body }}"> result.txt
        PR_FORMATTED_BODY=$(cat ./result.txt)
        echo "PR_FORMATTED_BODY<<EOF" >> $GITHUB_ENV
        echo "$PR_FORMATTED_BODY" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV        
      shell: bash
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: changelog
        SLACK_USERNAME: 'ghActionsBot'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_COLOR: '#90DBA4'
        SLACK_TITLE: Changelog notification for a Nomad software promotion
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: |
          ${{ env.PR_FORMATTED_BODY }}
