name: Promotion dev1->prod1 Slack notification
on:
  pull_request_target:
    types:
      - closed
    branches:
# FROM HERE Change to work on Nomad Action    
      - main
jobs:
  promoted_to_prod:
    if: |
      (
      github.event.pull_request.merged == true
      )
# TO HERE
    runs-on: ubuntu-latest
    env:
      NOTIFICATION_TITLE: "Changelog notification for a Nomad software promotion"

    steps:
    - name: PR Log title
      run: |
        echo "New promotion: ${{ github.event.pull_request.title }}"
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: PR Format body
      shell: bash
      working-directory: .github/workflows/changelog/
      # Multiline strings from: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      env:
        # PR_SHA: ${{ github.event.pull_request.head.sha }}
        BODY: ${{ github.event.pull_request.body }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PROMOTION_TITLE: ${{ github.event.pull_request.title }}
      run: |
        PR_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$PR_NUMBER"
        GITHUB_PARAMS="{ 'actor': '$GITHUB_ACTOR', 'repo': '$GITHUB_REPOSITORY', 'ref': '$GITHUB_REF', 'pr_url': '$PR_URL' }"
        python3 format_pr_body.py "${{ env.NOTIFICATION_TITLE }}" "$PROMOTION_TITLE" "$BODY" "$GITHUB_PARAMS"> result.txt
        PR_FORMATTED_BODY=$(cat result.txt)
        echo "PR_FORMATTED_BODY<<EOF" >> $GITHUB_ENV
        echo "$PR_FORMATTED_BODY" >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Slack Notify
      shell: bash
      env:
        BLOCKS: ${{ env.PR_FORMATTED_BODY }}
        # Title won't render if blocks is present but will show up in notifications
        # https://api.slack.com/messaging/attachments-to-blocks#fallback_text
        TIT: ${{ env.TITLE }}
      run: |
          curl --location --request POST "${{ secrets.SLACK_WEBHOOK }}" \
          --header 'Content-type: application/json' \
          --data "{\"channel\": \"#changelog\", \"username\": \"ghActionsBot\", \"icon_emoji\": \":github:\", "text": \"$TIT\", "blocks": $BLOCKS}"
