name: Promotion dev1->prod1 Slack notification
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
jobs:
  promoted_to_prod:
    if: |
      (
      github.event.pull_request.merged == true
      )
    runs-on: ubuntu-latest
    steps:
    - name: PR Log title
      run: |
        echo "New promotion: ${{ github.event.pull_request.title }}"
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: PR Format body
      working-directory: .github/workflows/changelog/
      # Multiline strings from: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      env:
        BODY: ${{ github.event.pull_request.body }}
      run: |
        python3 save_formated_pr_body.py "$BODY" > result.txt
        PR_FORMATTED_BODY=$(cat result.txt)
        echo "PR_FORMATTED_BODY<<EOF" >> $GITHUB_ENV
        echo "$PR_FORMATTED_BODY" >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash
    - name: Slack Notify
      env:
        MESSAGE: ${{ env.PR_FORMATTED_BODY }}
        BLOCKS: '[{"type": "section", "text": {"type": "mrkdwn", "text": "Danny Torrence left the following review for your property:"}]'
        TITLE: "Changelog notification for a Nomad software promotion ***"
      run: |
          curl --location --request POST "${{ secrets.SLACK_WEBHOOK }}" \
          --header 'Content-type: application/json; charset=utf-8' \
          --data ${{ format(' ''channel''': ''#githubchangelog'', ''username'': ''ghActionsBot'', ''icon_emoji'': '':github:'', ''text'': {0}', "$TITLE") }}
#          "blocks": "$BLOCKS"
