name: Promotion dev1->prod1 Slack notification
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
jobs:
  promoted_to_prod:
    if: |
      (
      github.event.pull_request.merged == true
      )
    runs-on: ubuntu-latest
    steps:
    - name: PR Log title
      run: |
        echo "New promotion: ${{ github.event.pull_request.title }}"
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: PR Format body
      working-directory: .github/workflows/changelog/
      # Multiline strings from: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      # ' "  %27 %22
      run: |
        body=${{ github.event.pull_request.body }}
        python3 save_formated_pr_body.py "${body//'%22'/' '}" > result.txt  
        PR_FORMATTED_BODY=$(cat result.txt)
        echo "PR_FORMATTED_BODY<<EOF" >> $GITHUB_ENV
        echo "$PR_FORMATTED_BODY" >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: changelog
        SLACK_USERNAME: 'ghActionsBot'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_COLOR: '#90DBA4'
        SLACK_TITLE: Changelog notification for a Nomad software promotion
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: |
          ${{ env.PR_FORMATTED_BODY }}
