name: Test of script
on:
  push:
    branches:
      - 'Formating-PR-Body'

jobs:
  testing_scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Log step
      run: |
        echo The PR was merged: ${{ github.event.pull_request.title }}
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Run script
      env:
        pr_body: ${{ github.event.pull_request.body}}
      run: |
        echo "***** $pr_body *****"
        ./format.sh
      shell: bash
