name: Promotion dev1->prod1 Slack notification
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
jobs:
  promoted_to_prod:
    if: |
      (
      github.event.pull_request.merged == true
      )
    runs-on: ubuntu-latest
    steps:
    - name: Log step
      run: |
        echo "New promotion: ${{ github.event.pull_request.title }}"
    - name: Checkout source code
      uses: actions/checkout@v3
      # with:
      #   repository: NomadHealth/nomad-env
      #   ref: Master
    - name: Run script
      id: run_script
      working-directory: ./
      run: |
        python3 save_formated_pr_body.py "${{ github.event.pull_request.body}}"> result.txt
      shell: bash
    - name: Print results
      run: |
        PR_FORMATTED_BODY::$(cat ./result.txt)
        echo "$PR_FORMATTED_BODY"
