name: Promotion dev1->prod1 Slack notification
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'

jobs:
  promoted_to_prod:
    if: |
      (
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'promote') &&
      contains(github.event.pull_request.labels.*.name, 'dev1→prod1')
      )
    runs-on: ubuntu-latest
    steps:
    - name: PR Merged
      run: |
        echo The PR was merged: ${{ github.event.pull_request.title }}"
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: githubchangelog
        SLACK_TITLE: ${{ github.event.pull_request.title}}
        SLACK_MESSAGE: |
          There was a Production deployment. It contained the following tickets:

          Jira Code | Description | Owner | Github Url
          --------------------------------------------------
          ${{ github.event.pull_request.body}}
