name: Test of script
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

env:
  PR_BODY: ${{ github.event.pull_request.body}}
  PR_FORMATTED_BODY: ""

jobs:
  promoted_to_prod:
    if: |
      (
      github.event.pull_request.merged == true
      )
    runs-on: ubuntu-latest
    steps:
    - name: Log step
      run: |
        echo New promotion: ${{ github.event.pull_request.title }}
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Run script
      run: |
        python3 save_formated_pr_body.py "$PR_BODY">> result.txt
        echo "::set-output name=PR_FORMATTED_BODY::$(cat ./result.txt)"
      shell: bash
    - name: Print results
      run: |
        echo *** ${{ github.event.pull_request.title }} ***
        echo ${{ env.PR_FORMATTED_BODY }}
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: githubchangelog
        SLACK_TITLE: ${{ github.event.pull_request.title }}
        SLACK_MESSAGE: |
          AQUI VOY
          ${{ env.PR_FORMATTED_BODY }}
